---
- name: Create swap file
  sudo: yes
  command: fallocate -l 4G /swapfile
           creates=/swapfile

- name: Change swap file permissions
  sudo: yes
  file: path=/swapfile
        mode=0600

- name: Check swap file type
  sudo: yes
  command: file /swapfile
  register: swapfile
  changed_when: False

- name: Start using swap file
  sudo: yes
  command: mkswap /swapfile
  when: swapfile.stdout.find('swap file') == -1

- name: Commit swap file to fstab
  sudo: yes
  mount:
    name=none
    src=/swapfile
    fstype=swap
    opts=sw
    passno=0
    dump=0
    state=present

- name: Mount swap
  sudo: yes
  command: swapon /swapfile
  when: ansible_swaptotal_mb < 1

- name: Install common base packages
  sudo: yes
  apt:
    name={{ item }}
    state=latest
    update_cache=yes
    cache_valid_time=3600
  with_items:
    - fail2ban
    - emacs24-nox
    - htop
    - tree
    - git
    - screen
    - ufw

- name: Configure default firewall rules
  sudo: yes
  ufw:
    direction={{ item.direction }}
    policy={{ item.policy }}
  with_items:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }

- name: Configure base firewall rule to allow SSH
  sudo: yes
  ufw:
    rule={{ item.rule }}
    port={{ item.port }}
    proto={{ item.proto }}
  with_items:
    - { rule: 'limit', port: '22', proto: 'tcp' }

- name: Enable firewall logging
  sudo: yes
  ufw: logging=on
  notify:
    - restart firewall

- name: Enable firewall
  sudo: yes
  ufw: state=enabled

- name: Configure git
  sudo: yes
  sudo_user: "{{ remote_user_name }}"
  template:
    src=.gitconfig.j2
    dest=~/.gitconfig